name: Protobuf
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master
      - uses: technote-space/get-diff-action@98fd8d380c6026fd0564d5a6f98fa2cf5c100c95 # v1
        id: git_diff
        with:
          SUFFIX_FILTER: .proto
          SET_ENV_NAME_INSERTIONS: 1
          SET_ENV_NAME_LINES: 1
      - name: lint
        run: make proto-lint-docker
        if: "env.GIT_DIFF != ''"
  breakage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master
      - uses: technote-space/get-diff-action@98fd8d380c6026fd0564d5a6f98fa2cf5c100c95 # v1
        id: git_diff
        with:
          SUFFIX_FILTER: .proto
          SET_ENV_NAME_INSERTIONS: 1
          SET_ENV_NAME_LINES: 1
      - name: check-breakage
        run: make proto-check-breaking-docker
        if: "env.GIT_DIFF != ''"
